#! /bin/bash

poetry remove langchain
docker build -t commune/backend_build -f build.Dockerfile .
VERSION=$(toml get --toml-path pyproject.toml tool.poetry.version)
docker build --build-arg VERSION=$VERSION -t ibiscp/blockflow_backend:$VERSION .
docker run -p 5003:80 -d ibiscp/blockflow_backend:$VERSION
poetry add --editable ../../../langchain
