version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/blockflow  # add this line to set PYTHONPATH

  frontend:
    build: ./blockflow/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./blockflow/frontend:/app
